docker-compose/AB.yml, docker-compose/ABQB.yml
1. 建议使用独立的 network 以支持 hostname 寻址，Ref：https://docs.docker.com/network/bridge/
2. 调整缩进
=> Docker compose 文件调整

.gitignore, .idea/.gitignore, .vscode/launch.json, .vscode/settings.json, AutoBangumi/app/RSSFilter.py, AutoBangumi/app/RssFilter/fliter_base.py, AutoBangumi/app/auto_set_rule.py, AutoBangumi/app/collect_bangumi_info.py, AutoBangumi/app/docker_main.py, AutoBangumi/app/env.py, AutoBangumi/app/get_full_season.py, AutoBangumi/app/rename_qb.py, Windows/win_main.py, old version/Docker/rename_qb.py, old version/rename_qb.py, old version/rule_set.py
- use logging module instead of print
- format by black
- use utf-8 as default encoding on log and file operate
- fix use undefined var
实际文件改动感觉有点过多了，可能不太好，先道歉（逃
本意是想给 Jellyfin 适配文件夹和文件命名，在修改的过程中发现一些可以优化的地方，所以先改了一版。
尽量没有动整体结构，只是做了一些上述小优化，不过十分建议如果可能的话，还是对项目能整体重构一下，也便于社区贡献。
我发现最新是有 RSSFilter 的提交，但是没有被实际用到。我觉得可能需要一个单独的模块可以作为 parser 处理文件名，获取所有信息，然后被其他模块调用，目前的项目好像有点各自为阵，parsing 文件名的地方很多。感觉是正在做这方面的 refactor，在完成之前我如果想实现一些定制的话，也需要做类似的修改，所以还是等大佬完成。
此外格式化插件因为项目中没有给出，常用的标准似乎和项目原始代码都不太一致。我希望可以和项目保持一致，还请作者可以告知或者添加进 requirements_dev.txt，我会相应修改提交。如果没有确定的话，也可以简单统一都用 black，比较省心。
最后非常感谢作者贡献这个项目，真的太神了，追番神器！
=> refactor and minor bug fix

auto_bangumi/parser/analyser/raw_parser.py, auto_bangumi/test.sh, auto_bangumi/tests/test_raw_parser.py
raw parser 这里看了一下并不需要将 Episode 存到变量里，直接返回应该比较好
然后发现没有单元测试，加了一下
re 我也准备改一下，可以提前 compile 一下，对性能或多或少有些提升。
没有完全改完，处理名字的地方有那么一点点乱。
=> 修改了下 Raw Parser 的格式，加了单元测试

src/parser/analyser/raw_parser.py
如：
```
[LoliHouse] 文豪野犬 第四季 / Bungou Stray Dogs Season 4 - 01(38) [WebRip 1080p HEVC-10bit AAC][简繁内封字幕]
```
=> 修复额外剧集序号的解析

docs/docker-compose/qBittorrent+AutoBangumi/docker-compose.yml
=> FIX doc docker-compose

src/main.py, src/module/conf/log.py, src/module/core/sub_thread.py, src/module/manager/renamer.py
Fixing [this issue](https://t.me/autobangumi/44073) by incorporating `src/data` existence check and `reset_log` into `setup_logger(..., reset=False)`.
=> Fix resetting logfile w/o releasing handler and late ensuring of data dir existence

src/module/notification/notification.py, src/module/notification/plugin/__init__.py, src/module/notification/plugin/wecom.py
=> Add Wecom Notification

src/module/conf/config.py
=> chore: enhance saving config file with non-ASCII

backend/src/main.py, backend/src/module/api/__init__.py, backend/src/module/api/auth.py, backend/src/module/api/bangumi.py, backend/src/module/api/config.py, backend/src/module/api/download.py, backend/src/module/api/log.py, backend/src/module/api/program.py, backend/src/module/api/proxy.py, backend/src/module/api/web.py
Make api routers be modular and isolated to avoid **circular import** problem
=> feat: make router be modular and isolated

webui/.husky/pre-commit, webui/package.json, webui/pnpm-lock.yaml, webui/src/components/ab-edit-rule.vue, webui/src/components/layout/ab-topbar.vue, webui/src/components/setting/config-notification.vue, webui/types/api.ts
cc @Rewrite0 
for this comment: https://github.com/EstrellaXD/Auto_Bangumi/pull/325#issuecomment-1586109585
=> feat: use husky to add git hooks before commiting code

backend/dev.sh
=> feat: use venv

backend/src/test/test_tmdb.py
=> ci: add more ci test

backend/src/module/rss/analyser.py, webui/src/api/search.ts, webui/src/components/ab-add-bangumi.vue, webui/src/components/ab-search-bar.vue, webui/src/components/basic/ab-search.vue, webui/src/components/layout/ab-topbar.vue, webui/src/pages/index/bangumi.vue, webui/src/store/search.ts, webui/types/dts/components.d.ts
- 更改搜索接口获取的 API 类型。
- 完成搜索添加功能的改造。
=> webui: 完成搜索组件的各类功能

docs/.vitepress/config.ts, docs/config/manager.md
=> Docs update

webui/src/components/basic/ab-switch.vue
=> style: change `AbSwitch` background color

backend/src/main.py, backend/src/module/checker/checker.py, backend/src/module/core/program.py, backend/src/module/core/status.py, backend/src/module/network/request_url.py, backend/src/module/parser/analyser/mikan_parser.py, backend/src/module/parser/analyser/tmdb_parser.py, backend/src/module/rss/analyser.py, backend/src/module/searcher/searcher.py, backend/src/module/update/__init__.py, backend/src/module/update/cross_version.py, backend/src/module/utils/__init__.py, backend/src/module/utils/cache_image.py, backend/src/test/test_tmdb.py, webui/vite.config.ts
Now AB can cache poster image in local storage for advanced usage.
=> feat: Local cache image

docs/deploy/docker-cli.md, docs/deploy/docker-compose.md, docs/deploy/dsm.md, docs/deploy/quick-start.md, docs/deploy/wsl.md, docs/docker-compose/AutoBangumi/docker-compose.yml, docs/docker-compose/qBittorrent+AutoBangumi/docker-compose.yml
=> docs: update docker and docker-compose

backend/src/module/parser/analyser/openai.py
replace event loop with `ThreadPoolExecutor`
#543
=> bugfix(openai): replace event loop with `ThreadPoolExecutor`

backend/src/module/models/config.py, backend/src/module/parser/analyser/openai.py, backend/src/test/test_openai.py, backend/src/test/test_title_parser.py, webui/src/components/setting/config-openai.vue, webui/src/i18n/en.json, webui/src/i18n/zh-CN.json, webui/types/config.ts
Now experimental openai has supported Microsoft Azure OpenAI!
#542
=> feat(openai): support Microsoft Azure OpenAI

backend/src/module/notification/plugin/telegram.py
=> fix telegram notification wrong when  no image

.github/workflows/build.yml
=> feat: Local deployment files are provided requirements.txt

docs/deploy/quick-start.md
As it can be confusing for people following the tutorial and don't know that's the default password here
=> [DOC] Add information of default username and password to Quick Start

backend/src/module/network/request_url.py
=> add decorator to RequestURL

backend/src/module/downloader/client/tr_downloader.py, backend/src/module/downloader/download_client.py, backend/src/module/models/config.py
完成了transmission下载器，基于httpx的rpc请求，对单个功能都进行了简单的测试，
其中transmission似乎是没有Category这个选项的，为了保证兼容性都用了label作为替代，在代码中都有标注。
=> feat(transmission): add transmission downloader

.github/ISSUE_TEMPLATE/bug_report.yml, README.md, backend/src/module/database/user.py
#608
测试过程中当密码长度小于 8 时会出现上述错误
```
2023-10-29 14:15:00 AutoBangumi  |   File "/app/module/api/auth.py", line 25, in login
2023-10-29 14:15:00 AutoBangumi  |     resp = auth_user(user)
2023-10-29 14:15:00 AutoBangumi  |            ^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/app/module/security/api.py", line 48, in auth_user
2023-10-29 14:15:00 AutoBangumi  |     resp = db.user.auth_user(user)
2023-10-29 14:15:00 AutoBangumi  |            ^^^^^^^^^^^^^^^^^^^^^^^
2023-10-29 14:15:00 AutoBangumi  |   File "/app/module/database/user.py", line 31, in auth_user
2023-10-29 14:15:00 AutoBangumi  |     if not verify_password(user.password, result.password):
```
user.password 为 None，原因如下:
```python
class User(SQLModel, table=True):
id: int = Field(default=None, primary_key=True) …
```
=> fix: incorrect password format

docs/config/proxy.md
=> Update proxy.md Reverse proxy

backend/src/module/models/config.py, backend/src/test/models/test_config.py
Automatically add api version for openai official base url.
=> bugfix(experimental): add api version for openai api base automatically

backend/src/module/parser/analyser/openai.py
https://platform.openai.com/docs/guides/text-generation/json-mode
resove: #759
=> fix(parser): fix parse gpt response error

backend/src/module/api/program.py, backend/src/module/core/program.py, backend/src/module/models/torrent.py, backend/src/module/network/request_contents.py, backend/src/module/parser/analyser/raw_parser.py, backend/src/module/parser/analyser/torrent_parser.py, backend/src/test/test_raw_parser.py, backend/src/test/test_torrent_parser.py
Reverts EstrellaXD/Auto_Bangumi#841
=> Revert "3.1.15"
